### ISSUE TITLE
Verbose output should go to stdout (not stderr)

### ISSUE THREAD

**Issue by dprince** [rackspace-titan/stacktester#52]
I've noticed that the verbose output seems to go to stderr instead of stdout.

For example the following output goes to stderr:

List all flavors ... ok
List all flavors in detail ... ok
Retrieve a single flavor ... ok
List all images in detail ... ok
List all images ... ok

**Comment by bcwaldon** [comment]
https://github.com/rackspace-titan/stacktester/pull/54
